import { REPO_URL } from "./branding";
import type {
  AnalyzeResponse,
  ReportBody,
  ReportType,
  RepoMeta,
} from "./types";

const FOOTER = `_Generated by [CommitArc](${REPO_URL})_`;

/** Full technical report markdown (analysis + AI + contributors + commits). */
export function buildReportMarkdown(
  repo: RepoMeta,
  body: ReportBody,
  aiText: string,
): string {
  const { rangeLabel, stats, commits } = body;
  const out: string[] = [];

  out.push(`# ${repo.fullName} — Commit Report`);
  out.push("");
  if (repo.description) out.push(`> ${repo.description}`);
  out.push("");
  out.push(`- **Range:** ${rangeLabel}`);
  out.push(`- **Visibility:** ${repo.private ? "private" : "public"}`);
  out.push(`- **Commits:** ${stats.totalCommits}`);
  if (stats.statsAvailable)
    out.push(
      `- **Changes:** +${stats.totalAdditions} / -${stats.totalDeletions} across ${stats.fileChanges} file-changes`,
    );
  out.push(`- **Contributors:** ${stats.authors.length}`);
  out.push("");

  if (aiText) {
    out.push("## AI Report");
    out.push("");
    out.push(aiText.trim());
    out.push("");
  }

  if (stats.authors.length) {
    out.push("## Contributors");
    out.push("");
    out.push("| Author | Commits | + | - |");
    out.push("|---|---:|---:|---:|");
    for (const a of stats.authors) {
      const name = a.login ? `${a.name} (@${a.login})` : a.name;
      out.push(`| ${name} | ${a.commits} | ${a.additions} | ${a.deletions} |`);
    }
    out.push("");
  }

  out.push(`## Commits (${commits.length})`);
  out.push("");
  for (const c of commits) {
    const msg = c.message.trim();
    const date = c.date ? c.date.slice(0, 10) : "";
    const who = c.author.login ? `@${c.author.login}` : c.author.name;
    const st = c.stats ? ` (+${c.stats.additions}/-${c.stats.deletions})` : "";
    out.push(
      `- \`${c.shortSha}\` ${date} — ${msg.split("\n")[0]}${st} — ${who}`,
    );
    const rest = msg.split("\n").slice(1).join("\n").trim();
    if (rest) {
      for (const bl of rest.split("\n")) out.push(`  ${bl}`);
    }
  }
  out.push("");
  out.push("---");
  out.push(FOOTER);

  return out.join("\n");
}

/** Client-facing markdown — title + the report, no commit changelog. */
export function buildNarrativeMarkdown(
  repo: RepoMeta,
  body: ReportBody,
  text: string,
  label: string,
): string {
  return [
    `# ${repo.fullName} — ${label}`,
    "",
    `**Release:** ${body.rangeLabel}`,
    "",
    text.trim(),
    "",
    "---",
    FOOTER,
    "",
  ].join("\n");
}

export function reportLabel(type: ReportType): string {
  return type === "technical"
    ? "Technical Report"
    : type === "demo"
      ? "Product Demo"
      : "Client Presentation";
}

/** Build the markdown for a given report type from a stored record. */
export function markdownForReport(
  result: AnalyzeResponse,
  type: ReportType,
): string {
  const body: ReportBody = {
    rangeLabel: result.rangeLabel,
    truncated: result.truncated,
    commits: result.commits,
    stats: result.stats,
  };
  const text = result.reports[type]?.text ?? "";
  if (type === "technical") return buildReportMarkdown(result.repo, body, text);
  return buildNarrativeMarkdown(result.repo, body, text, reportLabel(type));
}
